### ISSUE TITLE
Rcon problem

### ISSUE THREAD

**Issue by josigamer** [Woovie/palworld-server-helper#1]
I thought your project was wonderful

But I'm having a problem when I run the command

!players
I get this error
![Screenshot_4](https://github.com/Woovie/palworld-server-helper/assets/50076918/25943d7b-3b58-4d55-a1ee-ccf94ccd7a16)

and when I try to kick someone I get this error
![Screenshot_5](https://github.com/Woovie/palworld-server-helper/assets/50076918/cd09b05e-aeba-4d81-a893-e2334c6f3d42)

**Comment by josigamer** [comment]
I'm currently using Windows, but it seems that the rcon command is trying to execute some files that I don't have

**Comment by Woovie** [comment]
Yeah sorry it's hardcoded. I have an update that will download rcon for Windows and deploy with it.

It's a little bit of a mess right now.

Here's the rcon I used: https://github.com/gorcon/rcon-cli

**Comment by Woovie** [comment]
Update this line for now:

https://github.com/Woovie/palworld-server-helper/blob/63ae65e111c9a5e6e7827e64294a0c45b8af2cab/bot.py#L27

**Comment by josigamer** [comment]
I was getting this error "RuntimeWarning: coroutine 'perform_rcon_command' was never awaited"
when using the kick and ban command

I needed to change the lines

```
result = perform_rcon_command(f"KickPlayer {steamid}")
result = perform_rcon_command(f"BanPlayer {steamid}")
```

for that:

```
result = await perform_rcon_command(f"KickPlayer {steamid}")
result = await perform_rcon_command(f"BanPlayer {steamid}")
```

**Comment by josigamer** [comment]
Now it appears to be working fine

**Comment by Woovie** [comment]
Glad you got it working. Do note I'll be doing a huge update so expect changes. I'll try to commit tonight. It should solve several issues and complexities 🤞

**Comment by Woovie** [comment]
I reviewed my code, cleaned up a few things, and pushed it here: https://github.com/Woovie/palworld-server-helper/commit/99b1afe9e3a99116ed26b89f5872cb2da7c010ce

I've set up a channel in my Discord if you want to discuss the script faster and get help or possibly add features.

https://discord.gg/ccyGETpetw

The issues mentioned here _should_ be fixed, but it still needs more testing in a pure Windows environment, I mostly wrote this in WSL. Please let me know if you still see issues.

**Comment by Woovie** [comment]
Okay I had more time, I went ahead and fully tested this in Windows. You do now need the Visual C++ Build Tools to run it, but everything works great. I'll update README with instructions on that.
